version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jellyseerr_server_1
      APP_PORT: 5055
      PROXY_AUTH_WHITELIST: "/api/*"
      PROXY_AUTH_ADD: "false"

  server:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
        - LOG_LEVEL=debug
        - TZ=Asia/Tashkent
        - PUID=1000
        - PGID=1000
    ports:
        - 5055:5055
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure