version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       environment:
            - LOG_LEVEL=debug
            - TZ=Asia/Tashkent
       ports:
            - 5055:5055
       volumes:
            - /home/umbrel/jellyseer/config:/app/config
       restart: unless-stopped