version: "3"
services:
  status_app:
    image: mrorbitman/status:latest
    ports:
      - 9090:9090
    volumes:
      - "/etc/os-release:/host_root/etc/os-release:ro"
      - "/etc/hostname:/host_root/etc/hostname:ro"
      - "/proc:/host_root/proc"
      - "/proc/mounts:/host_root/proc/mounts"
      - "/home:/home:ro"
      - "/tmp:/tmp:ro"
      - "/mnt:/mnt:ro"
      - "/media:/media:ro"
      - "/run/media:/run/media:ro"
    restart: unless-stopped

