version: "2"
services:
  app:
    container_name: status_app
    build: ${APP_DATA_DIR}/status/
    volumes:
      - "/etc/os-release:/host_root/etc/os-release:ro"
      - "/etc/hostname:/host_root/etc/hostname:ro"
      - "/proc:/host_root/proc"
      - "/proc/mounts:/host_root/proc/mounts"
      - "/home:/home:ro"
      - "/tmp:/tmp:ro"
      - "/mnt:/mnt:ro"
      - "/media:/media:ro"
      - "/run/media:/run/media:ro"
    network_mode: "host"
